### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by xtc-dev** [KevinNovak/discord.js-Rate-Limiter#1]
This isn't working for me, how would this be used with normal discord.js commands with an advanced command handler?

**Comment by KevinNovak** [comment]
Can you explain more about what specifically isn't working? If you haven't already, check out the [Example Usage](https://github.com/KevinNovak/discord.js-Rate-Limiter#example-usage) on the README.

**Comment by xtc-dev** [comment]
When using discord.js, it says undefined on the import line. I believe it's the {}s but I have no idea.

**Comment by KevinNovak** [comment]
Did you figure out the issue?

**Comment by xtc-dev** [comment]
No, but my friend just made one that worked. Thank you though.
